"""
emit_macros.py
==============
Emit ``paper/macros.tex`` -- ``\\newcommand`` definitions for every numeric
result quoted in the manuscript prose, so the text stays synchronised with the
reproducible experiment pass (``results/csv/headline.json``).  Do not edit the
generated file by hand.
"""
from __future__ import annotations

import os
import json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSVDIR = os.path.join(ROOT, "results", "csv")
OUT = os.path.join(ROOT, "paper", "macros.tex")


def main():
    h = json.load(open(os.path.join(CSVDIR, "headline.json")))
    b = h["base_totals"]
    c = h["codesign"]
    bl = h["blind"]
    sc = h["scaling"]
    m_lo, m_hi = int(sc[0][0]), int(sc[-1][0])

    defs = {
        "Cm": f"{h['m']}",
        "Cnt": f"{h['nt']}",
        "Cntot": f"{h['n']}",
        "CssaTraj": "200{,}000",
        # base per-incident
        "Cmttd": f"{b['MTTD']:.2f}",
        "Cmresp": f"{b['MResponse']:.2f}",
        "Cmttr": f"{b['MTTResolve']:.2f}",
        "Cebreach": f"{b['E_breach']:.2f}",
        "Cedenial": f"{b['E_denial_daysrv']:.2f}",
        "Cedataloss": f"{b['E_dataloss']:.2f}",
        "Cexposure": f"{b['E_exposure_daysrv']:.2f}",
        # headline structural
        "Cresdev": f"{h['resolution_dev_from_exp']:.2f}",
        # co-design
        "Csigstar": f"{c['sigma_D']:.2f}",
        "Ctaustar": f"{c['tau_b']:.0f}",
        "CJstar": f"{c['J']:.2f}",
        "CSstar": f"{c['S']:.2f}",
        "COstar": f"{c['O']:.2f}",
        "Cdenialstar": f"{c['E_denial_daysrv']:.2f}",
        "Cdatalossstar": f"{c['E_dataloss']:.2f}",
        "Cdenialdroppct": f"{100*(b['E_denial_daysrv']-c['E_denial_daysrv'])/b['E_denial_daysrv']:.0f}",
        # detection-blind penalty
        "Cblindtau": f"{bl['tau_blind']:.0f}",
        "Cblindpen": f"{100*bl['penalty_frac']:.0f}",
        # scaling range
        "CmLo": f"{m_lo}",
        "CmHi": f"{m_hi}",
        "CntLo": f"{int(sc[0][1])}",
        "CntHi": f"{int(sc[-1][1])}",
        "CbreachLo": f"{sc[0][4]:.2f}",
        "CbreachHi": f"{sc[-1][4]:.2f}",
        # top sensitivity driver on data loss
        "CsensTop": h["sens_dataloss_top"][0][0],
        # imperfect-restore robustness (at cov_r = 0.7)
        "CcovMttrPct": f"{100*h['coverage']['mttr_inflation_at_0p7']:.0f}",
        "CcovLossPct": f"{100*h['coverage']['dataloss_inflation_at_0p7']:.0f}",
    }
    with open(OUT, "w") as fh:
        fh.write("% Auto-generated by code/emit_macros.py -- do not edit by hand.\n")
        for k, v in defs.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"macros -> {OUT}  ({len(defs)} definitions)")


if __name__ == "__main__":
    main()
